In [1]:
import tensorflow as tf

In [2]:
#setting data
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34,31]

tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset = tf_dataset.filter(lambda x: x>0).map(lambda y: y*72).shuffle(2).batch(2)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

[1584 2232]
[1512 2304]
[2232 2448]


In [3]:
images_ds = tf.data.Dataset.list_files('PetImages/*/*', shuffle=False)

In [4]:
image_count = len(images_ds)
image_count

25002

In [5]:
for file in images_ds.take(5):
    print(file.numpy)

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=string, numpy=b'PetImages\\Cat\\0.jpg'>>
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=string, numpy=b'PetImages\\Cat\\1.jpg'>>
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=string, numpy=b'PetImages\\Cat\\10.jpg'>>
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=string, numpy=b'PetImages\\Cat\\100.jpg'>>
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=string, numpy=b'PetImages\\Cat\\1000.jpg'>>


In [13]:
images_ds = images_ds.shuffle(10000)
for file in images_ds.take(5):
    print(file.numpy)


<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=string, numpy=b'PetImages\\Cat\\11178.jpg'>>
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=string, numpy=b'PetImages\\Dog\\4518.jpg'>>
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=string, numpy=b'PetImages\\Dog\\2322.jpg'>>
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=string, numpy=b'PetImages\\Cat\\10170.jpg'>>
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=string, numpy=b'PetImages\\Cat\\5780.jpg'>>


In [ ]:
class=["cat","dog"]

In [16]:
train_size=int(image_count*0.8)
train_ds=images_ds.take(train_size)
test_ds=images_ds.skip(train_size)

In [17]:
len(train_ds)

20001

In [18]:
len(test_ds)

5001

In [22]:
def get_label(file_path):
    import os
    parts = tf.strings.split(file_path, os.path.sep)
    return parts[-2]

In [23]:
get_label('PetImages\\Cat\\11178.jpg')

<tf.Tensor: shape=(), dtype=string, numpy=b'Cat'>

In [26]:
def process_image(file_path):
    label = get_label(file_path)
    img = tf.io.read_file(file_path) # load the raw data from the file as a string
    img = tf.image.decode_jpeg(img)
    img = tf.image.resize(img, [128, 128])
    return img, label

In [27]:
img, label = process_image('PetImages\\Cat\\11178.jpg')
img.numpy()[:2]

array([[[2.03418579e+01, 7.48248291e+00, 1.53391296e+02],
        [2.45936279e+01, 6.79309082e+00, 1.51890625e+02],
        [1.60507812e+01, 8.13281250e+00, 1.49454224e+02],
        [2.98703613e+01, 3.25549316e+00, 1.51574219e+02],
        [1.15216675e+01, 1.11132812e+01, 1.55367188e+02],
        [4.04301147e+01, 0.00000000e+00, 1.59914490e+02],
        [1.57256470e+01, 8.27825928e+00, 1.60129822e+02],
        [2.59218750e+01, 5.35937500e+00, 1.48718750e+02],
        [2.64101562e+01, 5.35937500e+00, 1.48718750e+02],
        [2.80635376e+01, 4.51953125e+00, 1.48718750e+02],
        [2.99218750e+01, 3.35937500e+00, 1.48718750e+02],
        [3.09218750e+01, 2.71875000e+00, 1.48718750e+02],
        [3.09218750e+01, 2.71875000e+00, 1.48718750e+02],
        [2.99375000e+01, 3.36859131e+00, 1.48718750e+02],
        [2.59218750e+01, 5.35937500e+00, 1.48718750e+02],
        [2.59218750e+01, 5.35937500e+00, 1.48718750e+02],
        [2.59218750e+01, 5.35937500e+00, 1.48718750e+02],
        [2.592

In [28]:
train_ds = train_ds.map(process_image)
test_ds = test_ds.map(process_image)

In [29]:
for image, label in train_ds.take(1):
    print("****",image)
    print("****",label)

**** tf.Tensor(
[[[ 76.706055   89.706055   69.706055 ]
  [ 74.92383    87.92383    67.92383  ]
  [ 70.28125    83.28125    63.28125  ]
  ...
  [124.890625  123.890625  154.89062  ]
  [122.53125   121.53125   152.53125  ]
  [123.484375  120.484375  151.48438  ]]

 [[ 74.29004    87.29004    67.29004  ]
  [ 78.57324    91.57324    71.57324  ]
  [ 74.674805   87.674805   67.674805 ]
  ...
  [118.87793   116.65625   143.09668  ]
  [120.23926   118.09375   144.27051  ]
  [119.5625    115.75      142.21875  ]]

 [[ 77.95508    90.95508    70.95508  ]
  [ 79.018555   92.018555   72.018555 ]
  [ 81.53125    94.53125    74.53125  ]
  ...
  [128.19824   126.88574   144.44824  ]
  [128.93457   127.62207   145.18457  ]
  [121.5       118.5       136.75     ]]

 ...

 [[ 60.51953    79.51953    51.51953  ]
  [ 51.21582    70.21582    42.21582  ]
  [ 43.293945   62.55957    34.55957  ]
  ...
  [ 58.654297   73.211914   51.460938 ]
  [ 70.92871    76.725586   60.381836 ]
  [ 89.07617    90.76367    

In [30]:
def scale(image, label):
    return image/255, label

In [31]:
train_ds = train_ds.map(scale)

In [32]:
for image, label in train_ds.take(5):
    print("****Image: ",image.numpy()[0][0])
    print("****Label: ",label.numpy())

****Image:  [0.7176471 0.7137255 0.7058824]
****Label:  b'Cat'
****Image:  [0.45219058 0.5223499  0.56070775]
****Label:  b'Cat'
****Image:  [0.4468585  0.42725065 0.40372124]
****Label:  b'Cat'
****Image:  [0.5092634  0.48965555 0.51418066]
****Label:  b'Dog'
****Image:  [0.07807115 0.04474571 0.04276123]
****Label:  b'Cat'
