In [15]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding



In [16]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [17]:
one_hot('poor service',30)

[16, 8]

In [18]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[28, 27], [12, 19], [16, 3], [11, 6, 14], [4, 16, 11], [29, 27], [17, 16, 10], [16, 8], [16, 5], [23, 25]]


In [19]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[28 27  0  0]
 [12 19  0  0]
 [16  3  0  0]
 [11  6 14  0]
 [ 4 16 11  0]
 [29 27  0  0]
 [17 16 10  0]
 [16  8  0  0]
 [16  5  0  0]
 [23 25  0  0]]


In [20]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [21]:
X = padded_reviews
y = sentiment

In [22]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten_1 (Flatten)         (None, 20)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [23]:
model.fit(X, y, epochs=50, verbose=0)

In [24]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 86ms/step - loss: 0.6368 - accuracy: 0.9000


0.8999999761581421

In [25]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [26]:
weights[4]

array([-0.0868848 ,  0.0361124 , -0.09803636,  0.04305263, -0.01890041],
      dtype=float32)